### ISSUE TITLE
Movie search not working

### ISSUE THREAD

**Issue by krotz** [griff/metaz#173]
My MetaZ has stopped functioning ever since I upgraded to High Sierra.  When I try to open files (either by selecting Open or dropping them into the window), it just hangs ... is this a known issue?  Thanks!

**Comment by rogermeier** [comment]
The latest beta should resolve this issue: https://github.com/griff/metaz/releases

**Comment by krotz** [comment]
That did it!  Thank you!   I still cannot get it to work for movies, even when i input the movie title and year, but i had that issue with the earlier release as well.  I mostly use for TV shows, however, so not a big deal....

Thank you again!

**Comment by rogermeier** [comment]
I believe setting the media type to "Movie" should resolve this issue as
well.

**Comment by DanielNonnweiler** [comment]
I updatet to Version 1.0.beta-34 (17.09.27.22.35f4f80) and also changed media type to movie.
But still no go

**Comment by krotz** [comment]
Same here .... TV shows work great, but nothing for movies.  I put in the movie title and video type, and it doesn’t even seem to search.  This hasn’t worked for me for years.  Are there any other settings in the Preferences I need to work about?  Thanks!

**Comment by griff** [comment]
@krotz @DanielNonnweiler That is odd. Can I get you to look at Preferences and see if The Movie Db plugin is enabled? And if it not you need to enable it and if it is can I get you to look in the log (it is in menu Help -> View Log) and attach it as a comment or send it to me at brian at maven-group dot org

**Comment by krotz** [comment]
I confirmed that the Movie DB plugin is enabled.  I just tried to do this
again with another movie, and it did not work.  The log, plus two screen
shots, are attached.

Thank you.

John

**Comment by griff** [comment]
@krotz I think github has filtered out the attachments so they don't appear in the comment on github.

**Comment by krotz** [comment]
How is this:

2017-11-20 08:44:48.999 MetaZ[3682:795985] Deprecated Binding Warning:
'data' binding of class PosterView is deprecated. You will only see this
warning once.

2017-11-20 08:44:49.034 MetaZ[3682:795985] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 08:44:49.037 MetaZ[3682:795985] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/TheTVDBPlugin.mzsearchprovider'

2017-11-20 08:44:49.037 MetaZ[3682:795985] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/OSXNotificationPlugin.mzactions'

2017-11-20 08:44:49.038 MetaZ[3682:795985] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/TheMovieDb.mzsearchprovider'

2017-11-20 08:44:49.039 MetaZ[3682:795985] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/Add to iTunes.scpt'

2017-11-20 08:44:49.039 MetaZ[3682:795985] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/Quit MetaZ.scpt'

2017-11-20 08:44:49.040 MetaZ[3682:795985] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/GrowlPlugin.mzactions'

2017-11-20 08:44:49.040 MetaZ[3682:795985] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ
2.app/Contents/PlugIns/AtomicParsleyPlugin.mzdataprovider'

2017-11-20 08:44:49.040 MetaZ[3682:795985] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/AlertWindowPlugin.mzactions'

2017-11-20 08:44:49.040 MetaZ[3682:795985] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/Example Actions.scpt'

2017-11-20 08:44:49.040 MetaZ[3682:795985] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/Update iTunes.scpt'

2017-11-20 08:44:49.044 MetaZ[3682:795985] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.TheTVDBPlugin'

2017-11-20 08:44:49.048 MetaZ[3682:795985] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.plugin.OSXNotificationPlugin'

2017-11-20 08:44:49.050 MetaZ[3682:795985] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.TheMovieDb'

2017-11-20 08:44:49.074 MetaZ[3682:795985] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin 'Add to iTunes'

2017-11-20 08:44:49.075 MetaZ[3682:795985] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin 'Quit MetaZ'

2017-11-20 08:44:49.078 MetaZ[3682:795985] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.plugin.GrowlPlugin'

2017-11-20 08:44:49.078 MetaZ[3682:795985] [lvl=1] -[MZMultiGrowlWrapper
load] path: /Applications/MetaZ
2.app/Contents/PlugIns/GrowlPlugin.mzactions/Contents/Frameworks/Growl.framework/Versions/1.3.1

2017-11-20 08:44:49.086 MetaZ[3682:795985] [lvl=2] -[MZMultiGrowlWrapper
load] Using Growl.framework 1.3.1 (1.3.1)

2017-11-20 08:44:49.206 MetaZ[3682:795985] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.AtomicParsleyPlugin'

2017-11-20 08:44:49.209 MetaZ[3682:795985] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.plugin.AlertWindowPlugin'

2017-11-20 08:44:49.210 MetaZ[3682:795985] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin 'Example Actions'

2017-11-20 08:44:49.211 MetaZ[3682:795985] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin 'Update iTunes'

2017-11-20 08:44:49.211 MetaZ[3682:795985] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 08:44:49.706 MetaZ[3682:796009] App Transport Security has
blocked a cleartext HTTP (http://) resource load since it is insecure.
Temporary exceptions can be configured via your app's Info.plist file.

objc[3682]: Class FIFinderSyncExtensionHost is implemented in both
/System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit
(0x7fffb302ea70) and
/System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride
(0x1108dacd8). One of the two will be used. Which one is undefined.

2017-11-20 08:45:12.953 MetaZ[3682:795985] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch AtomicParsley /Volumes/External Media Drive
3Tb/Movies/The Hitman's Bodyguard/The Hitman's Bodyguard.mp4 -t

2017-11-20 08:45:13.039 MetaZ[3682:795985] [lvl=1] -[MZParseTaskOperation
standardOutputGotData:] AtomicParsley stdout Atom "stik" contains: Short
Film

Atom "tvsn" contains:

Atom "tves" contains:

Atom "hdvd" contains:

Atom "com.apple.iTunes;iTunMOVI" contains: <?xml version="1.0"
encoding="UTF-8"?>

<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "
http://www.apple.com/DTDs/PropertyList-1.0.dtd">

<plist version="1.0">

<dict>

       <key>cast</key>

       <array>

              <dict>

                     <key>name</key>

                     <string>Ryan Reynolds</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Samuel L. Jackson</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Gary Oldman</string>

              </dict>

       </array>

       <key>directors</key>

       <array>

              <dict>

                     <key>name</key>

                     <string>Patrick Hughes</string>

              </dict>

       </array>

       <key>producers</key>

       <array/>

       <key>screenwriters</key>

       <array/>

</dict>

</plist>



Atom "com.apple.iTunes;iTunEXTC" contains: mpaa|R|400|

Atom "©nam" contains: The Hitman's Bodyguard

Atom "ldes" contains: The world's top bodyguard gets a new client, a hit
man who must testify at the International Court of Justice. They must put
their differences aside and work together to make it to the trial on time.

Atom "desc" contains: The world's top bodyguard gets a new client, a hit
man who must testify at the International Court of Justice. They must put
their differences aside and work together to make it to the trial on time.

Atom "©day" contains: 2017

Atom "©gen" contains: Action

Atom "covr" contains: 1 piece of artwork

2017-11-20 08:45:13.039 MetaZ[3682:795985] [lvl=1] -[AtomicParsleyPlugin
parseData:withFileName:dict:] Stik 'Short Film'

2017-11-20 08:45:13.039 MetaZ[3682:795985] [lvl=1] -[AtomicParsleyPlugin
parseData:withFileName:dict:] Genre Action

2017-11-20 08:45:13.039 MetaZ[3682:795985] [lvl=1] -[AtomicParsleyPlugin
parseData:withFileName:dict:] Rating mpaa|R|400|

2017-11-20 08:45:13.040 MetaZ[3682:795985] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch AtomicParsley /Volumes/External Media Drive
3Tb/Movies/The Hitman's Bodyguard/The Hitman's Bodyguard.mp4 -e
/var/folders/1_/hnv_q5056xn8h_x91cvd_5300000gn/T/MetaZImage_8FF3A29E-DE0D-4640-B0AB-C9B0F3FD5ACD-3682-00004C815D1C2F1B

2017-11-20 08:45:13.060 MetaZ[3682:795985] [lvl=1] -[MZTaskOperation
standardOutputGotData:] AtomicParsley stdout Extracted artwork to file:
/var/folders/1_/hnv_q5056xn8h_x91cvd_5300000gn/T/MetaZImage_8FF3A29E-DE0D-4640-B0AB-C9B0F3FD5ACD-3682-00004C815D1C2F1B_artwork_1.png

No changes.

2017-11-20 08:45:13.064 MetaZ[3682:795985] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch mp4chaps -l /Volumes/External Media Drive
3Tb/Movies/The Hitman's Bodyguard/The Hitman's Bodyguard.mp4

2017-11-20 08:45:13.180 MetaZ[3682:795985] [lvl=1] -[MZParseTaskOperation
standardOutputGotData:] mp4chaps stdout Duration 01:58:17.121

File "/Volumes/External Media Drive 3Tb/Movies/The Hitman's Bodyguard/The
Hitman's Bodyguard.mp4 does not contain chapters of type QuickTime and Nero

2017-11-20 08:45:13.297 MetaZ[3682:795985] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 08:45:13.297 MetaZ[3682:795985] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:00:03.258 MetaZ[3861:823998] Deprecated Binding Warning:
'data' binding of class PosterView is deprecated. You will only see this
warning once.

2017-11-20 09:00:03.289 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:00:03.290 MetaZ[3861:823998] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/TheTVDBPlugin.mzsearchprovider'

2017-11-20 09:00:03.290 MetaZ[3861:823998] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/OSXNotificationPlugin.mzactions'

2017-11-20 09:00:03.291 MetaZ[3861:823998] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/TheMovieDb.mzsearchprovider'

2017-11-20 09:00:03.291 MetaZ[3861:823998] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/Add to iTunes.scpt'

2017-11-20 09:00:03.291 MetaZ[3861:823998] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/Quit MetaZ.scpt'

2017-11-20 09:00:03.291 MetaZ[3861:823998] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/GrowlPlugin.mzactions'

2017-11-20 09:00:03.291 MetaZ[3861:823998] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ
2.app/Contents/PlugIns/AtomicParsleyPlugin.mzdataprovider'

2017-11-20 09:00:03.291 MetaZ[3861:823998] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/AlertWindowPlugin.mzactions'

2017-11-20 09:00:03.292 MetaZ[3861:823998] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/Example Actions.scpt'

2017-11-20 09:00:03.292 MetaZ[3861:823998] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/Update iTunes.scpt'

2017-11-20 09:00:03.295 MetaZ[3861:823998] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.TheTVDBPlugin'

2017-11-20 09:00:03.298 MetaZ[3861:823998] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.plugin.OSXNotificationPlugin'

2017-11-20 09:00:03.301 MetaZ[3861:823998] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.TheMovieDb'

2017-11-20 09:00:03.323 MetaZ[3861:823998] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin 'Add to iTunes'

2017-11-20 09:00:03.324 MetaZ[3861:823998] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin 'Quit MetaZ'

2017-11-20 09:00:03.327 MetaZ[3861:823998] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.plugin.GrowlPlugin'

2017-11-20 09:00:03.327 MetaZ[3861:823998] [lvl=1] -[MZMultiGrowlWrapper
load] path: /Applications/MetaZ
2.app/Contents/PlugIns/GrowlPlugin.mzactions/Contents/Frameworks/Growl.framework/Versions/1.3.1

2017-11-20 09:00:03.334 MetaZ[3861:823998] [lvl=2] -[MZMultiGrowlWrapper
load] Using Growl.framework 1.3.1 (1.3.1)

2017-11-20 09:00:03.426 MetaZ[3861:823998] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.AtomicParsleyPlugin'

2017-11-20 09:00:03.428 MetaZ[3861:823998] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.plugin.AlertWindowPlugin'

2017-11-20 09:00:03.429 MetaZ[3861:823998] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin 'Example Actions'

2017-11-20 09:00:03.430 MetaZ[3861:823998] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin 'Update iTunes'

2017-11-20 09:00:03.430 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

objc[3861]: Class FIFinderSyncExtensionHost is implemented in both
/System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit
(0x7fffb302ea70) and
/System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride
(0x1118f6cd8). One of the two will be used. Which one is undefined.

2017-11-20 09:02:40.564 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch AtomicParsley /Users/KrotzerRomanoff/Movies/Logan
Lucky (2017) [1080p] [YTS.AG]/Logan.Lucky.2017.1080p.BluRay.x264-[YTS.AG].mp4
-t

2017-11-20 09:02:40.601 MetaZ[3861:823998] [lvl=1] -[MZParseTaskOperation
standardOutputGotData:] AtomicParsley stdout Atom "©too" contains:
Lavf57.22.100

2017-11-20 09:02:40.602 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch AtomicParsley /Users/KrotzerRomanoff/Movies/Logan
Lucky (2017) [1080p] [YTS.AG]/Logan.Lucky.2017.1080p.BluRay.x264-[YTS.AG].mp4
-e
/var/folders/1_/hnv_q5056xn8h_x91cvd_5300000gn/T/MetaZImage_F50B1BFF-B537-43F8-A3DC-E769748BDFD4-3861-00004D754427E753

2017-11-20 09:02:42.727 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch mp4chaps -l /Users/KrotzerRomanoff/Movies/Logan
Lucky (2017) [1080p] [YTS.AG]/Logan.Lucky.2017.1080p.BluRay.x264-[YTS.AG
].mp4

2017-11-20 09:02:42.731 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
standardOutputGotData:] AtomicParsley stdout No changes.

2017-11-20 09:02:42.994 MetaZ[3861:823998] [lvl=1] -[MZParseTaskOperation
standardOutputGotData:] mp4chaps stdout Duration 01:59:03.222

File "/Users/KrotzerRomanoff/Movies/Logan Lucky (2017) [1080p] [YTS.AG
]/Logan.Lucky.2017.1080p.BluRay.x264-[YTS.AG].mp4 does not contain chapters
of type QuickTime and Nero

2017-11-20 09:02:43.130 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:02:43.130 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:02:56.031 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:02:56.033 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:02:59.735 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:02:59.736 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:06:41.644 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:06:41.645 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:06:49.448 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch AtomicParsley
/Users/KrotzerRomanoff/Movies/Bobs.Burgers.S08E05.HDTV.mp4 -t

2017-11-20 09:06:49.451 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch AtomicParsley
/Users/KrotzerRomanoff/Movies/smilf.s01e03.web.mp4 -t

2017-11-20 09:06:49.453 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch AtomicParsley
/Users/KrotzerRomanoff/Movies/The.Last.Man.on.Earth.S04E07.HDTV.mp4 -t

2017-11-20 09:06:49.473 MetaZ[3861:823998] [lvl=1] -[MZParseTaskOperation
standardOutputGotData:] AtomicParsley stdout Atom "stik" contains:

Atom "tvsn" contains:

Atom "tves" contains:

Atom "hdvd" contains:

Atom "com.apple.iTunes;iTunMOVI" contains: <?xml version="1.0"
encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST
1.0//EN"  "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist
version="1.0"><dict><key>studio</key><string>studio</string><key>cast</key><array><dict><key>name</key><string></string></dict></array><key>directors</key><array><dict><key>name</key><string></string></dict></array><key>producers</key><array><dict><key>name</key><string></string></dict></array><key>codirectors</key><array><dict><key>name</key><string>codirector</string></dict></array><key>screenwriters</key><array><dict><key>name</key><string></string></dict></array></dict></plist>

Atom "com.apple.iTunes;iTunEXTC" contains:

2017-11-20 09:06:49.474 MetaZ[3861:823998] [lvl=1] -[AtomicParsleyPlugin
parseData:withFileName:dict:] Stik ''

2017-11-20 09:06:49.474 MetaZ[3861:823998] [lvl=1] -[AtomicParsleyPlugin
parseData:withFileName:dict:] Rating

2017-11-20 09:06:49.474 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch AtomicParsley
/Users/KrotzerRomanoff/Movies/Bobs.Burgers.S08E05.HDTV.mp4 -e
/var/folders/1_/hnv_q5056xn8h_x91cvd_5300000gn/T/MetaZImage_95DAFECA-F0DF-4CA3-A277-4C1FF7EB4AFE-3861-00004DAF5A570AD5

2017-11-20 09:06:49.476 MetaZ[3861:823998] [lvl=1] -[MZParseTaskOperation
standardOutputGotData:] AtomicParsley stdout Atom "©too" contains:
Lavf55.33.100

Atom "stik" contains:

Atom "tvsn" contains:

Atom "tves" contains:

Atom "hdvd" contains:

Atom "com.apple.iTunes;iTunMOVI" contains: <?xml version="1.0"
encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST
1.0//EN"  "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist
version="1.0"><dict><key>studio</key><string>studio</string><key>cast</key><array><dict><key>name</key><string></string></dict></array><key>directors</key><array><dict><key>name</key><string></string></dict></array><key>producers</key><array><dict><key>name</key><string></string></dict></array><key>codirectors</key><array><dict><key>name</key><string>codirector</string></dict></array><key>screenwriters</key><array><dict><key>name</key><string></string></dict></array></dict></plist>

Atom "com.apple.iTunes;iTunEXTC" contains:

2017-11-20 09:06:49.476 MetaZ[3861:823998] [lvl=1] -[AtomicParsleyPlugin
parseData:withFileName:dict:] Stik ''

2017-11-20 09:06:49.476 MetaZ[3861:823998] [lvl=1] -[AtomicParsleyPlugin
parseData:withFileName:dict:] Rating

2017-11-20 09:06:49.476 MetaZ[3861:823998] [lvl=1] -[MZParseTaskOperation
standardOutputGotData:] AtomicParsley stdout Atom "©too" contains:
Lavf55.33.100

Atom "stik" contains:

Atom "tvsn" contains:

Atom "tves" contains:

Atom "hdvd" contains:

Atom "com.apple.iTunes;iTunMOVI" contains: <?xml version="1.0"
encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST
1.0//EN"  "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist
version="1.0"><dict><key>studio</key><string>studio</string><key>cast</key><array><dict><key>name</key><string></string></dict></array><key>directors</key><array><dict><key>name</key><string></string></dict></array><key>producers</key><array><dict><key>name</key><string></string></dict></array><key>codirectors</key><array><dict><key>name</key><string>codirector</string></dict></array><key>screenwriters</key><array><dict><key>name</key><string></string></dict></array></dict></plist>

Atom "com.apple.iTunes;iTunEXTC" contains:

2017-11-20 09:06:49.476 MetaZ[3861:823998] [lvl=1] -[AtomicParsleyPlugin
parseData:withFileName:dict:] Stik ''

2017-11-20 09:06:49.476 MetaZ[3861:823998] [lvl=1] -[AtomicParsleyPlugin
parseData:withFileName:dict:] Rating

2017-11-20 09:06:49.476 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch AtomicParsley
/Users/KrotzerRomanoff/Movies/smilf.s01e03.web.mp4 -e
/var/folders/1_/hnv_q5056xn8h_x91cvd_5300000gn/T/MetaZImage_3996D880-E6D8-49AB-B4E1-3C7ED638D2EF-3861-00004DAF5A7096DA

2017-11-20 09:06:49.478 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch AtomicParsley
/Users/KrotzerRomanoff/Movies/The.Last.Man.on.Earth.S04E07.HDTV.mp4 -e
/var/folders/1_/hnv_q5056xn8h_x91cvd_5300000gn/T/MetaZImage_76B7D534-723C-42C7-B79A-E7A0AE6E7DDA-3861-00004DAF5A7F968F

2017-11-20 09:06:49.487 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
standardOutputGotData:] AtomicParsley stdout No changes.

2017-11-20 09:06:49.489 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch mp4chaps -l
/Users/KrotzerRomanoff/Movies/Bobs.Burgers.S08E05.HDTV.mp4

2017-11-20 09:06:49.491 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
standardOutputGotData:] AtomicParsley stdout No changes.

2017-11-20 09:06:49.491 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch mp4chaps -l
/Users/KrotzerRomanoff/Movies/smilf.s01e03.web.mp4

2017-11-20 09:06:49.492 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch mp4chaps -l
/Users/KrotzerRomanoff/Movies/The.Last.Man.on.Earth.S04E07.HDTV.mp4

2017-11-20 09:06:49.494 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
standardOutputGotData:] AtomicParsley stdout No changes.

2017-11-20 09:06:49.526 MetaZ[3861:823998] [lvl=1] -[MZParseTaskOperation
standardOutputGotData:] mp4chaps stdout Duration 00:21:11.849

File "/Users/KrotzerRomanoff/Movies/Bobs.Burgers.S08E05.HDTV.mp4 does not
contain chapters of type QuickTime and Nero

2017-11-20 09:06:49.554 MetaZ[3861:823998] [lvl=1] -[MZParseTaskOperation
standardOutputGotData:] mp4chaps stdout Duration 00:28:20.500

File "/Users/KrotzerRomanoff/Movies/smilf.s01e03.web.mp4 does not contain
chapters of type QuickTime and Nero

2017-11-20 09:06:49.564 MetaZ[3861:823998] [lvl=1] -[MZParseTaskOperation
standardOutputGotData:] mp4chaps stdout Duration 00:21:30.580

File "/Users/KrotzerRomanoff/Movies/The.Last.Man.on.Earth.S04E07.HDTV.mp4
does not contain chapters of type QuickTime and Nero

2017-11-20 09:06:49.584 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:06:49.584 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:07:01.355 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:07:01.355 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:07:07.561 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:07:07.562 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:07:16.466 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:07:16.471 MetaZ[3861:823998] [lvl=1] -[TheTVDBPlugin
searchWithData:delegate:queue:] Sent request to TheTVDB

2017-11-20 09:07:17.577 MetaZ[3861:864443] App Transport Security has
blocked a cleartext HTTP (http://) resource load since it is insecure.
Temporary exceptions can be configured via your app's Info.plist file.

2017-11-20 09:07:17.580 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:07:20.314 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:07:20.332 MetaZ[3861:823998] [lvl=1] -[TheTVDBPlugin
searchWithData:delegate:queue:] Sent request to TheTVDB

2017-11-20 09:07:20.985 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:07:25.557 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:07:25.577 MetaZ[3861:823998] [lvl=1] -[TheTVDBPlugin
searchWithData:delegate:queue:] Sent request to TheTVDB

2017-11-20 09:07:26.176 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:07:30.004 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:07:30.017 MetaZ[3861:823998] [lvl=1] -[TheTVDBPlugin
searchWithData:delegate:queue:] Sent request to TheTVDB

2017-11-20 09:07:30.131 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:07:43.811 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch AtomicParsley /Volumes/External Media Drive
3Tb/TV Shows/SMILF/Season 1/01 A Box of Dunkies and Two Squirts of Maple
Syrup.mp4 -t

2017-11-20 09:07:43.863 MetaZ[3861:823998] [lvl=1] -[MZParseTaskOperation
standardOutputGotData:] AtomicParsley stdout Atom "stik" contains: TV Show

Atom "tvsn" contains: 1

Atom "tves" contains: 1

Atom "hdvd" contains:

Atom "com.apple.iTunes;iTunMOVI" contains: <?xml version="1.0"
encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST
1.0//EN"  "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist
version="1.0"><dict><key>studio</key><string>studio</string><key>cast</key><array><dict><key>name</key><string></string></dict></array><key>directors</key><array><dict><key>name</key><string></string></dict></array><key>producers</key><array><dict><key>name</key><string></string></dict></array><key>codirectors</key><array><dict><key>name</key><string>codirector</string></dict></array><key>screenwriters</key><array><dict><key>name</key><string></string></dict></array></dict></plist>

Atom "com.apple.iTunes;iTunEXTC" contains: us-tv|TV-MA|600|

Atom "desc" contains: Concerned that giving birth has blown out her vagina,
Bridgette pursues a former hookup for a comparison test. Meanwhile, she
also learns that Rafi, her baby's father, is dating someone new.

Atom "tvsh" contains: SMILF

Atom "©day" contains: 2017-11-05T11:00:00Z

Atom "©nam" contains: A Box of Dunkies and Two Squirts of Maple Syrup

Atom "ldes" contains: Concerned that giving birth has blown out her vagina,
Bridgette pursues a former hookup for a comparison test. Meanwhile, she
also learns that Rafi, her baby's father, is dating someone new.

Atom "©ART" contains: SMILF

Atom "gnre" contains: Comedy

Atom "tvnn" contains: Showtime

Atom "trkn" contains: 1

Atom "covr" contains: 1 piece of artwork

2017-11-20 09:07:43.864 MetaZ[3861:823998] [lvl=1] -[AtomicParsleyPlugin
parseData:withFileName:dict:] Stik 'TV Show'

2017-11-20 09:07:43.864 MetaZ[3861:823998] [lvl=1] -[AtomicParsleyPlugin
parseData:withFileName:dict:] Genre Comedy

2017-11-20 09:07:43.864 MetaZ[3861:823998] [lvl=1] -[AtomicParsleyPlugin
parseData:withFileName:dict:] Rating us-tv|TV-MA|600|

2017-11-20 09:07:43.864 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch AtomicParsley /Volumes/External Media Drive
3Tb/TV Shows/SMILF/Season 1/01 A Box of Dunkies and Two Squirts of Maple
Syrup.mp4 -e
/var/folders/1_/hnv_q5056xn8h_x91cvd_5300000gn/T/MetaZImage_DAFFC51D-9FA0-4514-A943-33C58C1AD0B3-3861-00004DBBE22F0AAF

2017-11-20 09:07:43.878 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
standardOutputGotData:] AtomicParsley stdout Extracted artwork to file:
/var/folders/1_/hnv_q5056xn8h_x91cvd_5300000gn/T/MetaZImage_DAFFC51D-9FA0-4514-A943-33C58C1AD0B3-3861-00004DBBE22F0AAF_artwork_1.png

No changes.

2017-11-20 09:07:43.879 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch mp4chaps -l /Volumes/External Media Drive 3Tb/TV
Shows/SMILF/Season 1/01 A Box of Dunkies and Two Squirts of Maple Syrup.mp4

2017-11-20 09:07:43.937 MetaZ[3861:823998] [lvl=1] -[MZParseTaskOperation
standardOutputGotData:] mp4chaps stdout Duration 00:31:39.160

File "/Volumes/External Media Drive 3Tb/TV Shows/SMILF/Season 1/01 A Box of
Dunkies and Two Squirts of Maple Syrup.mp4 does not contain chapters of
type QuickTime and Nero

2017-11-20 09:07:45.023 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:07:45.024 MetaZ[3861:823998] [lvl=1] -[TheTVDBPlugin
searchWithData:delegate:queue:] Sent request to TheTVDB

2017-11-20 09:07:45.131 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:07:48.285 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:07:48.288 MetaZ[3861:823998] [lvl=1] -[TheTVDBPlugin
searchWithData:delegate:queue:] Sent request to TheTVDB

2017-11-20 09:07:48.413 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:07:51.430 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:07:51.431 MetaZ[3861:823998] [lvl=1] -[TheTVDBPlugin
searchWithData:delegate:queue:] Sent request to TheTVDB

2017-11-20 09:07:51.553 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:07:53.009 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:07:53.010 MetaZ[3861:823998] [lvl=1] -[TheTVDBPlugin
searchWithData:delegate:queue:] Sent request to TheTVDB

2017-11-20 09:07:53.166 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:07:54.953 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:07:54.954 MetaZ[3861:823998] [lvl=1] -[TheTVDBPlugin
searchWithData:delegate:queue:] Sent request to TheTVDB

2017-11-20 09:07:55.361 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:07:55.633 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:07:55.634 MetaZ[3861:823998] [lvl=1] -[TheTVDBPlugin
searchWithData:delegate:queue:] Sent request to TheTVDB

2017-11-20 09:07:55.725 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:07:56.446 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:07:56.447 MetaZ[3861:823998] [lvl=1] -[TheTVDBPlugin
searchWithData:delegate:queue:] Sent request to TheTVDB

2017-11-20 09:07:56.628 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:07:57.844 MetaZ[3861:823998] [lvl=1] -[AtomicParsleyPlugin
saveChanges:delegate:queue:] Video type 10

2017-11-20 09:07:57.844 MetaZ[3861:823998] [lvl=1] -[AtomicParsleyPlugin
saveChanges:delegate:queue:] Rating 11

2017-11-20 09:07:57.932 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch AtomicParsley
/Users/KrotzerRomanoff/Movies/Bobs.Burgers.S08E05.HDTV.mp4 --output
/Users/KrotzerRomanoff/Movies/Bobs.Burgers.S08E05.HDTV MetaZ.mp4
--TVEpisodeNum 5 --TVSeasonNum 8 --TVNetwork FOX (US) --description When
Teddy’s family unexpectedly announces that they’re coming for Thanksgiving,
the Belchers reluctantly agree to pitch in. The preparation proves to be
much more challenging than they had anticipated, especially upon
discovering that Teddy is a secret hoarder. --TVShowName Bob's Burgers
--title Thanks-hoarding --year 2017-11-19T11:00:00Z --longDescription When
Teddy’s family unexpectedly announces that they’re coming for Thanksgiving,
the Belchers reluctantly agree to pitch in. The preparation proves to be
much more challenging than they had anticipated, especially upon
discovering that Teddy is a secret hoarder. --genre Animation --stik
value=10 --rDNSatom us-tv|TV-14|500| name=iTunEXTC domain=com.apple.iTunes
--tracknum 5 --album Bob's Burgers, Season 8 --albumArtist Bob's Burgers
--artist Bob's Burgers --artwork REMOVE_ALL --artwork
/var/folders/1_/hnv_q5056xn8h_x91cvd_5300000gn/T/MetaZImage_59E90A55-FB91-4FAA-AEC1-385B8F584213-3861-00004DBF476E665E.png
--rDNSatom <?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "
http://www.apple.com/DTDs/PropertyList-1.0.dtd">

<plist version="1.0">

<dict>

       <key>cast</key>

       <array>

              <dict>

                     <key>name</key>

                     <string>H. Jon Benjamin</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>John Roberts</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Kristen Schaal</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Larry Murphy</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Dan Mintz</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Eugene Mirman</string>

              </dict>

       </array>

       <key>directors</key>

       <array/>

       <key>producers</key>

       <array/>

       <key>screenwriters</key>

       <array/>

</dict>

</plist>

 name=iTunMOVI domain=com.apple.iTunes

2017-11-20 09:07:57.934 MetaZ[3861:823998] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 09:07:57.935 MetaZ[3861:823998] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

2017-11-20 09:07:58.238 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 10 '

 Started writing to temp file.

10'

2017-11-20 09:07:58.467 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 20 '20'

2017-11-20 09:07:58.752 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 30 '30'

2017-11-20 09:07:59.030 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 40 '40'

2017-11-20 09:07:59.300 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 50 '50'

2017-11-20 09:07:59.571 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 60 '60'

2017-11-20 09:07:59.828 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 70 '70'

2017-11-20 09:08:00.067 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 80 '80'

2017-11-20 09:08:00.313 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 90 '90'

2017-11-20 09:08:00.589 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 100 '100'

2017-11-20 09:08:00.601 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 0 '

 Finished writing to temp file.

'

2017-11-20 09:08:00.603 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 0 ''

2017-11-20 09:08:00.603 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 0 ''

2017-11-20 09:08:00.604 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 0 ''

2017-11-20 09:08:00.604 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch mp4chaps -l
/Users/KrotzerRomanoff/Movies/Bobs.Burgers.S08E05.HDTV MetaZ.mp4

2017-11-20 09:08:00.709 MetaZ[3861:823998] [lvl=1] -[MZParseTaskOperation
standardOutputGotData:] mp4chaps stdout Duration 00:21:11.849

File "/Users/KrotzerRomanoff/Movies/Bobs.Burgers.S08E05.HDTV MetaZ.mp4 does
not contain chapters of type QuickTime and Nero

2017-11-20 09:08:07.934 MetaZ[3861:823998] [lvl=1] -[AtomicParsleyPlugin
saveChanges:delegate:queue:] Video type 10

2017-11-20 09:08:07.934 MetaZ[3861:823998] [lvl=1] -[AtomicParsleyPlugin
saveChanges:delegate:queue:] Rating 12

2017-11-20 09:08:07.960 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch AtomicParsley
/Users/KrotzerRomanoff/Movies/smilf.s01e03.web.mp4 --output
/Users/KrotzerRomanoff/Movies/smilf.s01e03.web MetaZ.mp4 --TVEpisodeNum 3
--TVSeasonNum 1 --TVNetwork Showtime --description Nelson convinces Bridge
to use visualization techniques to improve her life. Inspired by Eliza's
financial success with an online venture, a broke Bridge takes to
Craigslist for some fast cash. --TVShowName SMILF --title Half a Sheet Cake
& a Blue-Raspberry Slushie --year 2017-11-19T11:00:00Z --longDescription
Nelson convinces Bridge to use visualization techniques to improve her
life. Inspired by Eliza's financial success with an online venture, a broke
Bridge takes to Craigslist for some fast cash. --genre Comedy --stik
value=10 --rDNSatom us-tv|TV-MA|600| name=iTunEXTC domain=com.apple.iTunes
--tracknum 3 --album SMILF, Season 1 --albumArtist SMILF --artist SMILF
--artwork REMOVE_ALL --artwork
/var/folders/1_/hnv_q5056xn8h_x91cvd_5300000gn/T/MetaZImage_01B981E0-2478-4066-A745-80DB71BD0791-3861-00004DC1A0D432C4.png
--rDNSatom <?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "
http://www.apple.com/DTDs/PropertyList-1.0.dtd">

<plist version="1.0">

<dict>

       <key>cast</key>

       <array>

              <dict>

                     <key>name</key>

                     <string>Adrian Ciscato</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Frankie Shaw</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Kimberley Crossman</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Mia Kaplan</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Miguel Gomez</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Rosie O'Donnell</string>

              </dict>

       </array>

       <key>directors</key>

       <array/>

       <key>producers</key>

       <array/>

       <key>screenwriters</key>

       <array/>

</dict>

</plist>

 name=iTunMOVI domain=com.apple.iTunes

2017-11-20 09:08:08.144 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 10 '

 Started writing to temp file.

10'

2017-11-20 09:08:08.320 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 20 '20'

2017-11-20 09:08:08.504 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 30 '30'

2017-11-20 09:08:08.690 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 40 '40'

2017-11-20 09:08:08.866 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 50 '50'

2017-11-20 09:08:09.048 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 60 '60'

2017-11-20 09:08:09.236 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 70 '70'

2017-11-20 09:08:09.430 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 80 '80'

2017-11-20 09:08:09.632 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 90 '90'

2017-11-20 09:08:09.819 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 100 '100'

2017-11-20 09:08:09.826 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 0 '

 Finished writing to temp file.

'

2017-11-20 09:08:09.827 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 0 ''

2017-11-20 09:08:09.828 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 0 ''

2017-11-20 09:08:09.828 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 0 ''

2017-11-20 09:08:09.828 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 0 ''

2017-11-20 09:08:09.829 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch mp4chaps -l
/Users/KrotzerRomanoff/Movies/smilf.s01e03.web MetaZ.mp4

2017-11-20 09:08:09.908 MetaZ[3861:823998] [lvl=1] -[MZParseTaskOperation
standardOutputGotData:] mp4chaps stdout Duration 00:28:20.500

File "/Users/KrotzerRomanoff/Movies/smilf.s01e03.web MetaZ.mp4 does not
contain chapters of type QuickTime and Nero

2017-11-20 09:08:12.806 MetaZ[3861:823998] [lvl=1] -[AtomicParsleyPlugin
saveChanges:delegate:queue:] Video type 10

2017-11-20 09:08:12.807 MetaZ[3861:823998] [lvl=1] -[AtomicParsleyPlugin
saveChanges:delegate:queue:] Rating 11

2017-11-20 09:08:12.853 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch AtomicParsley
/Users/KrotzerRomanoff/Movies/The.Last.Man.on.Earth.S04E07.HDTV.mp4
--output /Users/KrotzerRomanoff/Movies/The.Last.Man.on.Earth.S04E07.HDTV
MetaZ.mp4 --title Gender Friender --longDescription Tandy goes to great
lengths to convince everyone he's a feminist. Meanwhile, Carol gets jealous
of the time that Gail spends with Erica and Dawn, and Todd tries to be a
father figure to Jasper. --TVNetwork FOX (US) --TVEpisodeNum 7 --TVShowName
The Last Man on Earth --year 2017-11-19T11:00:00Z --TVSeasonNum 4
--description Tandy goes to great lengths to convince everyone he's a
feminist. Meanwhile, Carol gets jealous of the time that Gail spends with
Erica and Dawn, and Todd tries to be a father figure to Jasper. --genre
Comedy --stik value=10 --rDNSatom us-tv|TV-14|500| name=iTunEXTC
domain=com.apple.iTunes --tracknum 7 --album The Last Man on Earth, Season
4 --albumArtist The Last Man on Earth --artist The Last Man on Earth
--artwork REMOVE_ALL --artwork
/var/folders/1_/hnv_q5056xn8h_x91cvd_5300000gn/T/MetaZImage_98D5F9C9-EC94-4AAB-AED2-52D9C5E6D563-3861-00004DC2C343E6D2.png
--rDNSatom <?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "
http://www.apple.com/DTDs/PropertyList-1.0.dtd">

<plist version="1.0">

<dict>

       <key>cast</key>

       <array>

              <dict>

                     <key>name</key>

                     <string>Will Forte</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Kristen Schaal</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Mel Rodriguez</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>January Jones</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Kenneth Choi</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Cleopatra Coleman</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Jason Sudeikis</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Mary Steenburgen</string>

              </dict>

              <dict>

                     <key>name</key>

                     <string>Boris Kodjoe</string>

              </dict>

       </array>

       <key>directors</key>

       <array/>

       <key>producers</key>

       <array/>

       <key>screenwriters</key>

       <array/>

</dict>

</plist>

 name=iTunMOVI domain=com.apple.iTunes

2017-11-20 09:08:12.993 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 10 '

 Started writing to temp file.

10'

2017-11-20 09:08:13.126 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 20 '20'

2017-11-20 09:08:13.266 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 30 '30'

2017-11-20 09:08:13.417 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 40 '40'

2017-11-20 09:08:13.567 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 50 '50'

2017-11-20 09:08:13.711 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 60 '60'

2017-11-20 09:08:13.866 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 70 '70'

2017-11-20 09:08:14.014 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 80 '80'

2017-11-20 09:08:14.167 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 90 '90'

2017-11-20 09:08:14.303 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 100 '100'

2017-11-20 09:08:14.327 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 0 '

 Finished writing to temp file.

'

2017-11-20 09:08:14.328 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 0 ''

2017-11-20 09:08:14.328 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 0 ''

2017-11-20 09:08:14.329 MetaZ[3861:823998] [lvl=1] -[APMainWriteTask
standardOutputGotData:] Got data: 0 ''

2017-11-20 09:08:14.329 MetaZ[3861:823998] [lvl=1] -[MZTaskOperation
startOnMainThread] Launch mp4chaps -l
/Users/KrotzerRomanoff/Movies/The.Last.Man.on.Earth.S04E07.HDTV MetaZ.mp4

2017-11-20 09:08:14.375 MetaZ[3861:823998] [lvl=1] -[MZParseTaskOperation
standardOutputGotData:] mp4chaps stdout Duration 00:21:30.580

File "/Users/KrotzerRomanoff/Movies/The.Last.Man.on.Earth.S04E07.HDTV
MetaZ.mp4 does not contain chapters of type QuickTime and Nero

2017-11-20 15:25:52.485 MetaZ[4535:1064409] Deprecated Binding Warning:
'data' binding of class PosterView is deprecated. You will only see this
warning once.

2017-11-20 15:25:52.551 MetaZ[4535:1064409] [lvl=2] -[SearchController
doSearch:] Starting search 1

2017-11-20 15:25:52.553 MetaZ[4535:1064409] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/TheTVDBPlugin.mzsearchprovider'

2017-11-20 15:25:52.553 MetaZ[4535:1064409] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/OSXNotificationPlugin.mzactions'

2017-11-20 15:25:52.553 MetaZ[4535:1064409] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/TheMovieDb.mzsearchprovider'

2017-11-20 15:25:52.553 MetaZ[4535:1064409] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/Add to iTunes.scpt'

2017-11-20 15:25:52.553 MetaZ[4535:1064409] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/Quit MetaZ.scpt'

2017-11-20 15:25:52.554 MetaZ[4535:1064409] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/GrowlPlugin.mzactions'

2017-11-20 15:25:52.554 MetaZ[4535:1064409] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ
2.app/Contents/PlugIns/AtomicParsleyPlugin.mzdataprovider'

2017-11-20 15:25:52.554 MetaZ[4535:1064409] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/AlertWindowPlugin.mzactions'

2017-11-20 15:25:52.554 MetaZ[4535:1064409] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/Example Actions.scpt'

2017-11-20 15:25:52.554 MetaZ[4535:1064409] [lvl=1] -[MZPluginController
loadPluginSourceWithName:fromURL:error:] Loading plugin at path
'/Applications/MetaZ 2.app/Contents/PlugIns/Update iTunes.scpt'

2017-11-20 15:25:52.558 MetaZ[4535:1064409] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.TheTVDBPlugin'

2017-11-20 15:25:52.560 MetaZ[4535:1064409] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.plugin.OSXNotificationPlugin'

2017-11-20 15:25:52.563 MetaZ[4535:1064409] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.TheMovieDb'

2017-11-20 15:25:52.591 MetaZ[4535:1064409] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin 'Add to iTunes'

2017-11-20 15:25:52.592 MetaZ[4535:1064409] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin 'Quit MetaZ'

2017-11-20 15:25:52.595 MetaZ[4535:1064409] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.plugin.GrowlPlugin'

2017-11-20 15:25:52.595 MetaZ[4535:1064409] [lvl=1] -[MZMultiGrowlWrapper
load] path: /Applications/MetaZ
2.app/Contents/PlugIns/GrowlPlugin.mzactions/Contents/Frameworks/Growl.framework/Versions/1.3.1

2017-11-20 15:25:52.601 MetaZ[4535:1064409] [lvl=2] -[MZMultiGrowlWrapper
load] Using Growl.framework 1.3.1 (1.3.1)

2017-11-20 15:25:52.708 MetaZ[4535:1064409] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.AtomicParsleyPlugin'

2017-11-20 15:25:52.710 MetaZ[4535:1064409] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin
'org.maven-group.metaz.plugin.AlertWindowPlugin'

2017-11-20 15:25:52.712 MetaZ[4535:1064409] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin 'Example Actions'

2017-11-20 15:25:52.713 MetaZ[4535:1064409] [lvl=2] -[MZPluginController
loadPluginFromSource:error:] Loaded plugin 'Update iTunes'

2017-11-20 15:25:52.714 MetaZ[4535:1064409] [lvl=1] -[SearchController
finishedSearch:] Finished search 0

**Comment by krotz** [comment]
Anything new on this?  I open the file, change the video type to "Movie", change the Title to the appropriate movie title (i.e. "Logan Lucky", and it never finds anything.  Doesn't appear to even search.  I confirmed the MovieDB plug-in is enabled.  Thanks!

**Comment by Scott-AR** [comment]
Very old question, I know, but I was having the same problem (v 1.1.3, Mac OS Mojave). I did a complete removal of MetaZ (using AppDelete), then downloaded MetaZ and reinstalled. Worked perfectly afterwards.
