### ISSUE TITLE
MetaZ Mac OS high Sierra

### ISSUE THREAD

**Issue by DanielNonnweiler** [griff/metaz#174]
After upgrading to Mac OS High Sierra. Files cannot be opened anymore

**Comment by rogermeier** [comment]
Duplicate of issue #173. The latest beta fixes this: https://github.com/griff/metaz/releases

**Comment by forgosh** [comment]
Still not functioning

**Comment by griff** [comment]
@forgosh How is it not functioning? Because as @rogermeier said the latest beta in https://github.com/griff/metaz/releases should fix this issue.

**Comment by forgosh** [comment]
I downloaded the latest beta but still cannot add any videos to the app.

Sent from my iPhone

On Nov 24, 2017, at 11:23 AM, Brian Olsen <notifications@github.com<mailto:notifications@github.com>> wrote:


@forgosh<https://github.com/forgosh> How is it not functioning? Because as @rogermeier<https://github.com/rogermeier> said the latest beta in https://github.com/griff/metaz/releases should fix this issue.

**Comment by ghost** [comment]
still not working on high sierra for me either :-(

**Comment by knghtbrd** [comment]
I can report that neither 1.0.beta-34 nor -35 are working for me under 10.13.1.  Videos are not recognized and nothing I type into the search box brings up any results.

**Comment by ajmas** [comment]
I had an issue where all I saw was a circle in the file list when it opened. Trying the new beta resolved things for me.

Do you see any errors in the /var/log/system.log that might indicated an issue, when you try opening files? Also, what file format are the files?

I am using macOS 10.13.2, in case the OS update helped?

**Comment by forgosh** [comment]
I was working with m4v and mp4 files. At the time, I was on the latest beta and had similar results (spinning beach ball). I didn’t see much of anything in the logs but could try again to see what shows up. Let me know if that would be of use.
Seth

**Comment by ajvera85** [comment]
I'm running Version 1.0a15 (13.11.27.14.8abfa83), downloaded and installed today.  High Sierra version is 10.13.2 (17C88).  The only problem I'm experiencing is the Files To Write field remains frozen with the circle. I can navigate through the settings, but the end result is the same - I can't edit any tags if the files don't load.  

Here's a screen shot:

![image](https://user-images.githubusercontent.com/30942753/34073303-7c0de790-e24b-11e7-99ad-3f7f2a39ccdc.png)

Here is the log from my run:

2017-12-16 10:18:54.295 MetaZ[25482:1180348] [lvl=2] -[SearchController doSearch:] Starting search 1
2017-12-16 10:18:54.298 MetaZ[25482:1180348] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/TheTVDBPlugin.mzsearchprovider'
2017-12-16 10:18:54.299 MetaZ[25482:1180348] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/OSXNotificationPlugin.mzactions'
2017-12-16 10:18:54.299 MetaZ[25482:1180348] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/TheMovieDb.mzsearchprovider'
2017-12-16 10:18:54.299 MetaZ[25482:1180348] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Add to iTunes.scpt'
2017-12-16 10:18:54.299 MetaZ[25482:1180348] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Quit MetaZ.scpt'
2017-12-16 10:18:54.299 MetaZ[25482:1180348] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/GrowlPlugin.mzactions'
2017-12-16 10:18:54.300 MetaZ[25482:1180348] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/AtomicParsleyPlugin.mzdataprovider'
2017-12-16 10:18:54.300 MetaZ[25482:1180348] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/AlertWindowPlugin.mzactions'
2017-12-16 10:18:54.300 MetaZ[25482:1180348] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/TagChimp.mzsearchprovider'
2017-12-16 10:18:54.300 MetaZ[25482:1180348] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Example Actions.scpt'
2017-12-16 10:18:54.301 MetaZ[25482:1180348] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Update iTunes.scpt'
2017-12-16 10:18:54.303 MetaZ[25482:1180348] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.TheTVDBPlugin'
2017-12-16 10:18:54.304 MetaZ[25482:1180348] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.plugin.OSXNotificationPlugin'
2017-12-16 10:18:54.306 MetaZ[25482:1180348] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.TheMovieDb'
2017-12-16 10:18:54.316 MetaZ[25482:1180348] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Add to iTunes'
2017-12-16 10:18:54.317 MetaZ[25482:1180348] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Quit MetaZ'
2017-12-16 10:18:54.318 MetaZ[25482:1180348] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.plugin.GrowlPlugin'
2017-12-16 10:18:54.318 MetaZ[25482:1180348] [lvl=1] -[MZMultiGrowlWrapper load] path: /Applications/MetaZ.app/Contents/PlugIns/GrowlPlugin.mzactions/Contents/Frameworks/Growl.framework/Versions/1.3.1
2017-12-16 10:18:54.321 MetaZ[25482:1180348] [lvl=2] -[MZMultiGrowlWrapper load] Using Growl.framework 1.3.1 (1.3.1)
2017-12-16 10:18:54.502 MetaZ[25482:1180348] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.AtomicParsleyPlugin'
2017-12-16 10:18:54.503 MetaZ[25482:1180348] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.plugin.AlertWindowPlugin'
2017-12-16 10:18:54.505 MetaZ[25482:1180348] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.TagChimp'
2017-12-16 10:18:54.506 MetaZ[25482:1180348] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Example Actions'
2017-12-16 10:18:54.507 MetaZ[25482:1180348] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Update iTunes'
2017-12-16 10:18:54.507 MetaZ[25482:1180348] [lvl=1] -[SearchController finishedSearch:] Finished search 0
2017-12-16 10:19:41.593 MetaZ[25482:1180348] [lvl=1] -[MZTaskOperation startOnMainThread] Launch AtomicParsley /Volumes/Inateck500GB/Movies/WW.m4v -t

**Comment by griff** [comment]
@ajvera85 You need to download the latest beta release since that fixes your problem. There are still problems with searching though.

**Comment by geerlingguy** [comment]
I can confirm that manually downloading the latest beta fixes the problem. Note that beta releases don't show if you open the app and do 'Check for Updates'; so even if the app reports it's up to date, you need to manually download the latest beta and replace your existing copy of MetaZ with it.

BTW, thanks @griff !

**Comment by ryanjbonnell** [comment]
The latest MetaZ beta still appears broken when adding files on High Sierra.

I'm using the most current beta from Github and the latest version of macOS:

> MetaZ 1.0.beta-35 (17.11.21.01.5908927).
> macOS 10.13.2 (17C88)

I get the same behavior in this screenshot:

![Screenshot](https://user-images.githubusercontent.com/30942753/34073303-7c0de790-e24b-11e7-99ad-3f7f2a39ccdc.png)

**Comment by griff** [comment]
@ryanjbonnell could I get you to look in the log and add it in a comment?

**Comment by ryanjbonnell** [comment]
Absolutely. Here's the relevant part of the log file when I drag a file onto the app icon in the Dock.

$ tail -f ~/Library/Logs/MetaZ.log

```
2018-01-06 12:52:49.837 MetaZ[17082:2403753] Deprecated Binding Warning: 'data' binding of class PosterView is deprecated. You will only see this warning once.
[...]
2018-01-06 12:50:23.888 MetaZ[16698:2394689] [lvl=1] -[MetaZApplication handleOpenScriptCommand:] Handle open: (
    "file:///Users/bonnell/Desktop/media.m4v"
) {
    "" =     (
        "file:///Users/bonnell/Desktop/media.m4v"
    );
}
```

MetaZ never responds after this point.

It's worth noting that pressing the "+" button to prompt a Finder dialog is also broken in the latest beta on High Sierra. Perhaps these bugs are related?

**Comment by griff** [comment]
@ryanjbonnell Is there no line in the log like this:

`
-[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/AtomicParsleyPlugin.mzdataprovider'
`

**Comment by ryanjbonnell** [comment]
I truncated the log file for brevity.

Here's the full contents of the log file:

```
2018-01-06 13:53:13.953 MetaZ[18814:2495822] Deprecated Binding Warning: 'data' binding of class PosterView is deprecated. You will only see this warning once.
2018-01-06 13:53:13.982 MetaZ[18814:2495822] [lvl=2] -[SearchController doSearch:] Starting search 1
2018-01-06 13:53:13.983 MetaZ[18814:2495822] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/TheTVDBPlugin.mzsearchprovider'
2018-01-06 13:53:13.984 MetaZ[18814:2495822] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/OSXNotificationPlugin.mzactions'
2018-01-06 13:53:13.984 MetaZ[18814:2495822] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/TheMovieDb.mzsearchprovider'
2018-01-06 13:53:13.984 MetaZ[18814:2495822] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Add to iTunes.scpt'
2018-01-06 13:53:13.984 MetaZ[18814:2495822] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Quit MetaZ.scpt'
2018-01-06 13:53:13.985 MetaZ[18814:2495822] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/GrowlPlugin.mzactions'
2018-01-06 13:53:13.985 MetaZ[18814:2495822] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/AtomicParsleyPlugin.mzdataprovider'
2018-01-06 13:53:13.985 MetaZ[18814:2495822] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/AlertWindowPlugin.mzactions'
2018-01-06 13:53:13.985 MetaZ[18814:2495822] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Example Actions.scpt'
2018-01-06 13:53:13.985 MetaZ[18814:2495822] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Update iTunes.scpt'
2018-01-06 13:53:13.988 MetaZ[18814:2495822] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.TheTVDBPlugin'
2018-01-06 13:53:13.991 MetaZ[18814:2495822] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.plugin.OSXNotificationPlugin'
2018-01-06 13:53:13.994 MetaZ[18814:2495822] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.TheMovieDb'
2018-01-06 13:53:14.011 MetaZ[18814:2495822] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Add to iTunes'
2018-01-06 13:53:14.012 MetaZ[18814:2495822] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Quit MetaZ'
2018-01-06 13:53:14.014 MetaZ[18814:2495822] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.plugin.GrowlPlugin'
2018-01-06 13:53:14.014 MetaZ[18814:2495822] [lvl=1] -[MZMultiGrowlWrapper load] path: /Applications/MetaZ.app/Contents/PlugIns/GrowlPlugin.mzactions/Contents/Frameworks/Growl.framework/Versions/1.3.1
2018-01-06 13:53:14.020 MetaZ[18814:2495822] [lvl=2] -[MZMultiGrowlWrapper load] Using Growl.framework 1.3.1 (1.3.1)
2018-01-06 13:53:14.138 MetaZ[18814:2495822] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.AtomicParsleyPlugin'
2018-01-06 13:53:14.140 MetaZ[18814:2495822] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.plugin.AlertWindowPlugin'
2018-01-06 13:53:14.142 MetaZ[18814:2495822] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Example Actions'
2018-01-06 13:53:14.143 MetaZ[18814:2495822] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Update iTunes'
2018-01-06 13:53:14.144 MetaZ[18814:2495822] [lvl=1] -[SearchController finishedSearch:] Finished search 0
2018-01-06 13:53:14.885 MetaZ[18814:2495835] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
2018-01-06 13:54:12.495 MetaZ[18825:2497327] Deprecated Binding Warning: 'data' binding of class PosterView is deprecated. You will only see this warning once.
2018-01-06 13:54:12.526 MetaZ[18825:2497327] [lvl=2] -[SearchController doSearch:] Starting search 1
2018-01-06 13:54:12.527 MetaZ[18825:2497327] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/TheTVDBPlugin.mzsearchprovider'
2018-01-06 13:54:12.527 MetaZ[18825:2497327] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/OSXNotificationPlugin.mzactions'
2018-01-06 13:54:12.527 MetaZ[18825:2497327] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/TheMovieDb.mzsearchprovider'
2018-01-06 13:54:12.527 MetaZ[18825:2497327] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Add to iTunes.scpt'
2018-01-06 13:54:12.528 MetaZ[18825:2497327] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Quit MetaZ.scpt'
2018-01-06 13:54:12.528 MetaZ[18825:2497327] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/GrowlPlugin.mzactions'
2018-01-06 13:54:12.528 MetaZ[18825:2497327] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/AtomicParsleyPlugin.mzdataprovider'
2018-01-06 13:54:12.528 MetaZ[18825:2497327] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/AlertWindowPlugin.mzactions'
2018-01-06 13:54:12.529 MetaZ[18825:2497327] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Example Actions.scpt'
2018-01-06 13:54:12.529 MetaZ[18825:2497327] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Update iTunes.scpt'
2018-01-06 13:54:12.531 MetaZ[18825:2497327] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.TheTVDBPlugin'
2018-01-06 13:54:12.532 MetaZ[18825:2497327] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.plugin.OSXNotificationPlugin'
2018-01-06 13:54:12.534 MetaZ[18825:2497327] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.TheMovieDb'
2018-01-06 13:54:12.549 MetaZ[18825:2497327] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Add to iTunes'
2018-01-06 13:54:12.549 MetaZ[18825:2497327] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Quit MetaZ'
2018-01-06 13:54:12.551 MetaZ[18825:2497327] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.plugin.GrowlPlugin'
2018-01-06 13:54:12.551 MetaZ[18825:2497327] [lvl=1] -[MZMultiGrowlWrapper load] path: /Applications/MetaZ.app/Contents/PlugIns/GrowlPlugin.mzactions/Contents/Frameworks/Growl.framework/Versions/1.3.1
2018-01-06 13:54:12.555 MetaZ[18825:2497327] [lvl=2] -[MZMultiGrowlWrapper load] Using Growl.framework 1.3.1 (1.3.1)
2018-01-06 13:54:12.665 MetaZ[18825:2497327] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.AtomicParsleyPlugin'
2018-01-06 13:54:12.667 MetaZ[18825:2497327] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.plugin.AlertWindowPlugin'
2018-01-06 13:54:12.668 MetaZ[18825:2497327] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Example Actions'
2018-01-06 13:54:12.669 MetaZ[18825:2497327] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Update iTunes'
2018-01-06 13:54:12.670 MetaZ[18825:2497327] [lvl=1] -[SearchController finishedSearch:] Finished search 0
2018-01-06 13:54:12.994 MetaZ[18825:2497327] [lvl=1] -[MetaZApplication handleOpenScriptCommand:] Handle open: (
    "file:///Users/bonnell/Desktop/media.m4v"
) {
    "" =     (
        "file:///Users/bonnell/Desktop/media.m4v"
    );
}
```

**Comment by ryanjbonnell** [comment]
I did some independent testing of my own, and it appears that by **deleting the MetaZ preferences and downloading the latest beta release _works around the problem in High Sierra_**.

> For clarity, I can use the latest beta, 1.0.beta-35, and successfully edit the metadata of files on High Sierra!

After wiping my drive clean and installing a fresh copy of High Sierra, I used the macOS Migration Assistant to migrate my user preferences to my current install.

Having discovered this _accidental_ workaround, I wonder if there's something from MetaZ's preferences in 10.12 "Sierra" that causes the buggy behavior in 10.13 "High Sierra"?

**Comment by fortinne** [comment]
I deleted Meta Z and reloaded  1.0.beta-35, and now it works fine with High Sierra. The update feature within the app did not work.

**Comment by Kdisimone** [comment]
Thank you @griff .  Deleting old MetaZ application and installing the beta solved my High Sierra issue.

**Comment by clreply** [comment]
Still having same issue with High Sierra... Just formatted computer and did a clean install of OS, downloaded latest Beta but same problem. Been going on for some time, anyone have any ideas or workarounds? Alternate Apps?

![screen shot 2018-03-21 at 5 57 04 pm](https://user-images.githubusercontent.com/32654290/37739765-9ce51c6e-2d31-11e8-8224-60a5e9321577.png)

**Comment by clreply** [comment]
Still same problem... anyone know if this issue is every going to get completely resolved?
![screen shot 2018-03-27 at 3 56 55 pm](https://user-images.githubusercontent.com/32654290/37991618-a4b95e14-31d7-11e8-8c52-b77f984051a9.png)

**Comment by griff** [comment]
@clreply Could I get you to look in the log and attach it as a comment?

**Comment by griff** [comment]
@clreply And could I get you to use the latest beta release of MetaZ ([Beta 37](https://github.com/griff/metaz/releases/download/v1.0.beta-37/MetaZ-1.0.beta-37.zip)) since that has extra logging to try and locate the error, before you attach the log.

**Comment by clreply** [comment]
@griff The issue is occurring on two different computers, one running the latest version of macOS Sierra 10.12.6 and the other running macOS High Sierra 10.13.3.  Here's the log file for the public release of MetaZ
[MetaZ.log](https://github.com/griff/metaz/files/1860219/MetaZ.log)
![screen shot 2018-03-29 at 9 11 59 am](https://user-images.githubusercontent.com/32654290/38090903-fe3d4c2e-3331-11e8-8240-d40d340cad57.png)

**Comment by clreply** [comment]
Beta37 which was just released appears to have corrected the problem. Thank you!
What's the difference between beta 37 and 38?

**Comment by griff** [comment]
I thought it might be a good idea to explain in detail the cause of this issue and what I have done to fix it.

The problem described here (You try and open a file and it just shows the progress indicator and nothing else happens) are in fact two bugs that from a users perspective looks like the exact same problem.

The first bug is that something changed in High Sierra where the notification that a file was finished loading never got received. The problem was that the notification was sent for the value `isFinished` while the listening part was observing the value `finished`. In older versions of MacOS this just worked as they were considered the same value. But not so in High Sierra. This is the bug fixed in Beta 34.

The other bug is a sporadic problem that has been there a long time but I have never been able to pin down the exact reason for it happening. MetaZ has a plugin architecture where data loading, searching and notifications are their own blocks code that can be disabled and users can provide they own (though to my knowledge no one ever has). What plugins are disabled is stored in the MetaZ preferences but for some reason sometimes plugins would get disabled without the user doing anything. Specifically the only data loading plugin would get disabled leaving MetaZ unable to load any files. And because disabling the only data loading plugin doesn't make much sense it was never handled that well in MetaZ and so it would show seem like MetaZ was broken. To "fix" the problem I have now done several things:

1. More logging so that the logs show if a plugin is disabled
2. Don't allow data loading plugins to be disabled
3. Show an error to the user when a file could not be loaded because of a disabled data loading plugin

1 & 2 were done in Beta 37 and 3 was done in Beta 38 and is more a guard if I ever decide to revert 2

**Comment by clreply** [comment]
@griff Thank you for the detailed explanation, and for the thorough analysis of the of the Code to discover the root cause of the issues. More importantly, thanks for correcting both bugs in the latest Beta, it is greatly appreciated!!

**Comment by esvorm** [comment]
Currently using MetaZ beta-45 on OSX 10.13.6 High Sierra and the search function will not work. I can enter files and edit fields manually, but I cannot pull up any preexisting meta data from TheTVDB or others. Is this feature not available in Beta, or is this an actual bug? 

Thanks!
